name: PlayDisc
main: andreiwasfound.playdisc.Main
author: AndreiWasFound
version: 1.0.1 PUBLIC DEV
api-version: 1.13
description: Let's you play any disc in the game using /playdisc
website: https://www.spigotmc.org/resources/playdisc.82591/

commands:
  playdisc:
    description: Main info about this plugin
    permission: playdisc.use